### ISSUE TITLE
request no sent when setConnectionManagerShared is set to true

### ISSUE THREAD

**Issue by unoexperto** [Nowheresly/odoo-dev-docker#1]
Hi Sylvere ! I appologize for sending you message here. I just don't know how to contact you.

Could you please tell me what you've do to fix issue you reported here ? https://issues.apache.org/jira/browse/HTTPASYNC-83

**Comment by nowheresly** [comment]
I Ruslan,
I decided not to use setConnectionManagerShared(true) at all.
It is safe (and [recommended](http://stackoverflow.com/questions/26511437/is-multiple-httpasyncclients-considered-a-bad-practice/26512555#26512555)) to use the same instance of CloseableHttpAsyncClient as long as the connectionManager is a PoolingNHttpClientConnectionManager.
Be careful to size appropriately the PoolingNHttpClientConnectionManager instance. 
If you need to send different cookie values for each request, you have to manage it at the HttpGet object level.
I hope it helps...
